### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by Lizzetee** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Lizzetee#2]
[Infografía_Lizzete L..pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Lizzetee/files/9471325/Infografia_Lizzete.L.pdf)

**Comment by kirus21** [comment]
18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
